/**
 * WellnessResult.tsx
 * 
 * Renders the evaluation analysis generated by the wellnessEngine.
 * Color-codes stress risks (Low, Moderate, High) with high contrast.
 * Handles safety overrides using assertive ARIA live regions for crisis helplines.
 * 
 * Code Quality Updates: Added explicit React.ReactElement return type, imported helplines list
 * and responsible AI disclaimer from constants, and removed magic strings.
 */

import React from 'react';
import { WellnessInsights } from '../lib/types';
import { RESPONSIBLE_AI_NOTE, CRISIS_HELPLINES } from '../lib/constants';

interface WellnessResultProps {
  insights: WellnessInsights | null;
}

export const WellnessResult: React.FC<WellnessResultProps> = ({ insights }): React.ReactElement | null => {
  if (!insights) {
    return (
      <div 
        className="card" 
        style={{
          textAlign: 'center',
          padding: 'var(--spacing-xl)',
          color: 'var(--color-text-secondary)',
          borderStyle: 'dashed'
        }}
      >
        <p>No check-in insights generated yet. Complete the form above to see your diagnostic summary.</p>
      </div>
    );
  }

  // Choose alert styling class based on risk level
  const getRiskClass = (level: string): string => {
    switch (level) {
      case 'High': return 'alert alert-danger';
      case 'Moderate': return 'alert alert-warning';
      default: return 'alert alert-success';
    }
  };

  return (
    <section 
      className="card" 
      aria-labelledby="insights-heading"
      style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacing-md)' }}
    >
      <h2 id="insights-heading">Your Personalized Wellness Insights</h2>

      {/* ARIA Assertive live alert for Crisis Detection */}
      {insights.hasCrisis && (
        <div 
          className="alert alert-danger" 
          role="alert" 
          aria-live="assertive"
          style={{ padding: 'var(--spacing-lg)' }}
        >
          <h3 style={{ color: 'var(--color-risk-high)', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: 'var(--spacing-sm)' }}>
            ⚠️ Emergency & Safety Alert
          </h3>
          <p style={{ color: 'var(--color-risk-high)', margin: 'var(--spacing-sm) 0' }}>
            It sounds like you are experiencing a high level of distress. Please reach out for immediate support. You are not alone.
          </p>
          <div style={{ marginTop: 'var(--spacing-md)' }}>
            <h4 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--color-risk-high)', marginBottom: 'var(--spacing-xs)' }}>
              Emergency Helplines:
            </h4>
            <ul style={{ paddingLeft: 'var(--spacing-md)', display: 'flex', flexDirection: 'column', gap: 'var(--spacing-sm)' }}>
              {CRISIS_HELPLINES.map((line, idx) => (
                <li key={idx}>
                  <strong>{line.name}:</strong> {line.contact} ({line.details})
                </li>
              ))}
            </ul>
          </div>
          <p style={{ fontSize: '0.85rem', color: 'var(--color-risk-high)', marginTop: 'var(--spacing-md)' }}>
            <em>*ExamEase AI is an educational tracking companion, not an emergency clinical responder.*</em>
          </p>
        </div>
      )}

      {/* Stress Risk level indicator with polite live updates */}
      <div 
        className={getRiskClass(insights.riskLevel)} 
        role="status" 
        aria-live="polite"
        style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap' }}
      >
        <div>
          <span style={{ fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>
            Stress Risk Level
          </span>
          <h3 style={{ margin: 0, fontSize: '1.6rem', fontWeight: 700, color: 'inherit' }}>
            {insights.riskLevel} Risk
          </h3>
        </div>
        
        {insights.detectedTriggers.length > 0 && (
          <div style={{ display: 'flex', gap: 'var(--spacing-xs)', flexWrap: 'wrap', maxWidth: '300px' }}>
            {insights.detectedTriggers.map((trigger, idx) => (
              <span 
                key={idx} 
                style={{
                  fontSize: '0.75rem',
                  fontWeight: 600,
                  backgroundColor: 'rgba(0,0,0,0.08)',
                  padding: '4px 10px',
                  borderRadius: '12px',
                  color: 'inherit'
                }}
              >
                {trigger}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Wellness Insight Grid */}
      <div 
        className="grid-2" 
        style={{ marginTop: 'var(--spacing-sm)' }}
        role="region" 
        aria-label="Wellness Insight Details"
      >
        {/* Left column */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacing-md)' }}>
          <div style={{ borderLeft: '4px solid var(--color-primary)', paddingLeft: 'var(--spacing-md)' }}>
            <h3 style={{ fontSize: '1rem', textTransform: 'uppercase', color: 'var(--color-text-secondary)' }}>
              Emotional Pattern
            </h3>
            <p style={{ marginTop: 'var(--spacing-xs)' }}>{insights.emotionalPattern}</p>
          </div>

          <div style={{ borderLeft: '4px solid var(--color-secondary)', paddingLeft: 'var(--spacing-md)' }}>
            <h3 style={{ fontSize: '1rem', textTransform: 'uppercase', color: 'var(--color-text-secondary)' }}>
              Contextual Coping Strategy
            </h3>
            <p style={{ marginTop: 'var(--spacing-xs)' }}>{insights.copingStrategy}</p>
          </div>

          <div style={{ borderLeft: '4px solid var(--color-primary)', paddingLeft: 'var(--spacing-md)' }}>
            <h3 style={{ fontSize: '1rem', textTransform: 'uppercase', color: 'var(--color-text-secondary)' }}>
              Study Routine Optimization
            </h3>
            <p style={{ marginTop: 'var(--spacing-xs)' }}>{insights.studyWellnessRecommendation}</p>
          </div>
        </div>

        {/* Right column */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--spacing-md)' }}>
          <div style={{ backgroundColor: 'var(--color-primary-light)', padding: 'var(--spacing-md)', borderRadius: 'var(--radius-md)' }}>
            <h3 style={{ fontSize: '1rem', color: 'var(--color-primary)', display: 'flex', alignItems: 'center', gap: 'var(--spacing-xs)' }}>
              🧘 Adaptive Mindfulness Exercise
            </h3>
            <p style={{ marginTop: 'var(--spacing-sm)', color: 'var(--color-primary-hover)', fontWeight: 500 }}>
              {insights.mindfulnessExercise}
            </p>
          </div>

          <div style={{ backgroundColor: 'var(--color-secondary-light)', padding: 'var(--spacing-md)', borderRadius: 'var(--radius-md)' }}>
            <h3 style={{ fontSize: '1rem', color: 'var(--color-secondary)', display: 'flex', alignItems: 'center', gap: 'var(--spacing-xs)' }}>
              ✨ Motivational Encouragement
            </h3>
            <p style={{ marginTop: 'var(--spacing-sm)', color: 'var(--color-secondary)', fontWeight: 500 }}>
              {insights.motivationalEncouragement}
            </p>
          </div>
        </div>
      </div>

      {/* Responsible AI Disclaimer footer */}
      <footer 
        style={{
          marginTop: 'var(--spacing-md)',
          paddingTop: 'var(--spacing-md)',
          borderTop: '1px solid var(--color-border)',
          fontSize: '0.8rem',
          color: 'var(--color-text-secondary)',
          textAlign: 'center'
        }}
      >
        {RESPONSIBLE_AI_NOTE}
      </footer>
    </section>
  );
};
